import { ScanItem } from "../types";

export const SAMPLE_SCANS: ScanItem[] = [
  {
    id: "scan-sample-1",
    title: "Amazon Order Confirmation",
    category: "orders",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuDRqx4SOen-Smm4Gn3FqVidjQWH8l75Ue2wsbrMlYpK_d_P3U2Gu2snKdC0zuInAnLXGWrJ5133HCFplLQn3yX2nPHRsp_qn9yu-4tMKgDJ9GwtRE0Gyzq1NZwlKfonfPZMPvVNWxVHOsai6ctucDg1S5LeinP--MjnYiRsSNzW3QycowM3N8QvLkADUPAFSFV2u9eNBUjtzUAaQLmasS4fhMPnnSig3sQIHkDbr3WW9ZI6rMw8UYXH7g",
    timestamp: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
    roomCode: "default",
    status: "completed",
    confidence: 98,
    rawText: "Amazon Order #114-8921021. Tracking 1Z992A0129381. Status: Arriving Monday.",
    insights: [
      {
        id: "insight-order-1",
        type: "order",
        title: "Amazon Order #114-8921",
        subtitle: "Tracking: 1Z992A0129381 • Status: Arriving Monday",
        date: "Arriving Monday",
        trackingNumber: "1Z992A0129381",
        actionLabel: "Track Package",
        actionType: "tracking",
        completed: false,
      },
    ],
    deviceInfo: {
      deviceName: "iPhone 15 Pro",
      deviceType: "mobile",
    },
  },
  {
    id: "scan-sample-2",
    title: "AI Workshop Calendar Event",
    category: "events",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuDYoMsnMri-5QjtEiPoNnv9fkxeJ0jYPWi-MkVwRQbH1rUlkwr3YSLiU4YCzpRoF0xnIz9rQTuoHwxJtWYoekTTt53jhMj8HL14Sx_Km1y1efQf7MnHcn54Szpa0ViXHpn1W02_lvkqzU6GenS9CCdBujPaOO0Ljw7bkTdzWwxdXSW0vhLu2MG_aA29v8Y4TDay47_QmGagFys9rOPuQOM3xJmB4qYYsmtDV2H4riOrqBXGj-KEyrORIQ",
    timestamp: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    roomCode: "default",
    status: "completed",
    confidence: 95,
    rawText: "AI Workshop & Strategy Sync. August 15, 10:00 AM.",
    insights: [
      {
        id: "insight-event-1",
        type: "event",
        title: "AI Workshop & Strategy Sync",
        subtitle: "August 15 • 10:00 AM",
        date: "Aug 15",
        time: "10:00 AM",
        actionLabel: "Add to Calendar",
        actionType: "calendar",
        completed: false,
      },
    ],
    deviceInfo: {
      deviceName: "MacBook Pro 16",
      deviceType: "desktop",
    },
  },
  {
    id: "scan-sample-3",
    title: "Blue Bottle Coffee Receipt",
    category: "payments",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuBQqYgygYidhZc_xcuZxsnVYcPy2EINlUV1-jIctE493DEP4z6DKT1KR9fv4hJqCJlUoPikpd0prpEkoLuX1bXU8gW0bsUmOJIIds3gUf4d-2JgvRfUME_VHveAWUbjkx0XU1vkOuoYLBr1iut83c7XbBWTWGEwvNBOjcOlFU3n8soOewav9Phj1D-swm9O3QleLIGkdnI0OWgXLcBDCnPu_j6DVyZ5WAphXOgiz0AytR6DaPeD2lb9EQ",
    timestamp: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    roomCode: "default",
    status: "completed",
    confidence: 96,
    rawText: "Blue Bottle Coffee. Oat Flat White - $6.50. Paid via Apple Pay.",
    insights: [
      {
        id: "insight-payment-1",
        type: "payment",
        title: "Blue Bottle Coffee Expense",
        subtitle: "$6.50 • Oat Flat White",
        amount: "$6.50",
        actionLabel: "Log Expense",
        actionType: "expense",
        completed: true,
      },
    ],
    deviceInfo: {
      deviceName: "iPhone 15 Pro",
      deviceType: "mobile",
    },
  },
  {
    id: "scan-sample-4",
    title: "JAL Flight Boarding Pass to Tokyo",
    category: "flights",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuDMNEY-I0FBGBL1bR_cZ07Z8HU1hSQUM_lDDbMsH73whu1IS1nqiFOu7cDKMksejKWqfTcG6glLoUquiOdfZqz9pTolVZYmF3exCfIv5Sk7_lydqfbAgbBXySOHAKPSYyEN3Tp4oTUBJkiOTDQ7guIVgAfeimdu8vFkS0L8u9aBpK18ms9lujOdlCR_7tvh3hljiC0x0coePFAOCkfXd6UNxu7mIowCTH3kr4QZie-PAwWHxVT0IyPy5g",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
    roomCode: "default",
    status: "completed",
    confidence: 97,
    rawText: "Japan Airlines Boarding Pass JL 005 to Tokyo Narita. Departs 10:45 AM.",
    insights: [
      {
        id: "insight-flight-1",
        type: "flight",
        title: "JAL Flight JL 005 to Tokyo",
        subtitle: "Departs 10:45 AM • Gate 42B",
        time: "10:45 AM",
        actionLabel: "Add Flight to Itinerary",
        actionType: "calendar",
        completed: false,
      },
    ],
    deviceInfo: {
      deviceName: "iPad Pro",
      deviceType: "tablet",
    },
  },
  {
    id: "scan-sample-5",
    title: "123 Tech Lane Address",
    category: "locations",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuCDmLO0rCkXkwa4LRKBOBIWwmBmyTM9--9pVPauAtjPN678rVeUVCfqiSs636_MAmLOhIa2XVHeR4NZPAD53HVGQPmBHEYMiNOgVPTSlrh17LF47lyhHuxe6YZZztiI_0VeS_gQ6QNVoVDqASBVivNA18Oduau3bl0FdKNs77AdsDvnqu9sF2fiCovGN9Nzazuyvj3LlXe3Ic1cwi_6aL9Ty0hkuANnHFthPEArHOjBfuQ-HAK8Cfgnvg",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 22).toISOString(),
    roomCode: "default",
    status: "completed",
    confidence: 92,
    rawText: "123 Tech Lane, San Francisco, CA 94107",
    insights: [
      {
        id: "insight-location-1",
        type: "location",
        title: "123 Tech Lane",
        subtitle: "San Francisco, CA 94107",
        location: "123 Tech Lane, San Francisco, CA",
        actionLabel: "Open in Maps",
        actionType: "maps",
        completed: false,
      },
    ],
    deviceInfo: {
      deviceName: "MacBook Pro 16",
      deviceType: "desktop",
    },
  },
  {
    id: "scan-sample-6",
    title: "Grocery Shopping List Sticky Note",
    category: "tasks",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuAD1cLULkUHCl6S5meHL4oq49Xh0THJFQdMlH6p2pwb3vV0IwqHYVkxmPekng_ZH1kxHRucZHl686e6yg8g38hfmKtLjK8T2PYSCJjDR8CVq1wQCZKrKb47Oam_-oDfyi1uwQxuBYGQCvi-GDkvjjUCCYM7M_MrSiS2rLHIRfxR9NP7-stGR3418RI6X4xmgxe5hwt76yVoXO2Tl92rItmq43QNiOMu_C-trXfvpS5Q4hcHsPw9EzpsRg",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 30).toISOString(),
    roomCode: "default",
    status: "completed",
    confidence: 94,
    rawText: "Grocery items: Oat milk, Organic eggs, Avocados, Greek yogurt, Espresso beans",
    insights: [
      {
        id: "insight-task-1",
        type: "task",
        title: "Buy Oat Milk & Eggs",
        subtitle: "Grocery store shopping list",
        actionLabel: "Mark Complete",
        actionType: "todo",
        completed: false,
      },
      {
        id: "insight-task-2",
        type: "task",
        title: "Buy Espresso Beans & Greek Yogurt",
        subtitle: "Grocery store shopping list",
        actionLabel: "Mark Complete",
        actionType: "todo",
        completed: false,
      },
    ],
    deviceInfo: {
      deviceName: "iPhone 15 Pro",
      deviceType: "mobile",
    },
  },
];
